DROP SCHEMA IF EXISTS TRIP_PLANNER CASCADE;
CREATE SCHEMA IF NOT EXISTS TRIP_PLANNER;

SET search_path TO TRIP_PLANNER,public;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE PERSON
(
    ID         UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL,
    JOB_ROLE   VARCHAR(50) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    RATING     BOOLEAN NOT NULL
);

CREATE TABLE TRIP
(
    ID          UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    KIND        VARCHAR(255) NOT NULL,
    START_DATE  DATE NOT NULL,
    START_LOCATION VARCHAR(255) NOT NULL,
    END_DATE    DATE NOT NULL,
    END_LOCATION VARCHAR(255) NOT NULL
);

CREATE TABLE TRIP_REQUIRED_JOB_ROLE
(
    ID         UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    TRIP_ID    UUID NOT NULL,
    JOB_ROLE   VARCHAR(50) NOT NULL,
    REQUIRED_COUNT INT NOT NULL DEFAULT 1,
    CONSTRAINT FK_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIP (ID)
);

CREATE TABLE TRIP_REGISTRATION
(
    ID         UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    TRIP_ID    UUID NOT NULL,
    PERSON_ID  UUID NOT NULL,
    CONSTRAINT FK_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIP (ID),
    CONSTRAINT FK_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID)
);

COMMIT;